# Generated by Django 5.0.2 on 2024-02-27 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_location_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='postcode',
        ),
    ]
