# Generated by Django 5.0.2 on 2024-03-10 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_location_postcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='on_campus',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='location',
            name='type',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(db_index=True, max_length=256, unique=True),
        ),
    ]
