# Generated by Django 5.0.2 on 2024-03-10 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_location_name_location_on_campus_location_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
