# Generated by Django 5.0.2 on 2024-03-12 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_location_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
