# Generated by Django 5.0.2 on 2024-03-08 20:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_location_postcode'),
        ('user', '0002_alter_journey_time_logged'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journey',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='journey',
            name='origin',
        ),
        migrations.RemoveField(
            model_name='journey',
            name='time_logged',
        ),
        migrations.AddField(
            model_name='journey',
            name='carbon_savings',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='journey',
            name='direction',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='journey',
            name='off_campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.location'),
        ),
        migrations.AddField(
            model_name='journey',
            name='on_campus',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='journey',
            name='time_finished',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journey',
            name='time_started',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='active_journey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.journey'),
        ),
        migrations.AlterField(
            model_name='journey',
            name='distance',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
