# Generated by Django 5.0.2 on 2024-03-10 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_location_name_location_on_campus_location_type_and_more'),
        ('user', '0003_remove_journey_destination_remove_journey_origin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journey',
            name='direction',
        ),
        migrations.RemoveField(
            model_name='journey',
            name='off_campus',
        ),
        migrations.RemoveField(
            model_name='journey',
            name='on_campus',
        ),
        migrations.AddField(
            model_name='journey',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination', to='main.location'),
        ),
        migrations.AddField(
            model_name='journey',
            name='origin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin', to='main.location'),
        ),
    ]
