# Generated by Django 5.0.2 on 2024-03-15 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_badges_userbadge"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userbadge",
            name="id",
            field=models.AutoField(
                auto_created=True,
                default=0,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
