# Generated by Django 5.0.3 on 2024-03-19 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_badges_profile_streak_userbadge'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='flagged',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='journey',
            name='reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
