# Generated by Django 4.2.10 on 2024-03-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_journey_flagged_journey_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gamemaster',
            field=models.BooleanField(default=False),
        ),
    ]
