# Generated by Django 5.0.2 on 2024-02-27 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('address', models.CharField(max_length=256)),
                ('postcode', models.CharField(max_length=16)),
            ],
        ),
    ]
