# Generated by Django 5.0.2 on 2024-03-18 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('type', models.PositiveIntegerField()),
                ('target', models.PositiveIntegerField(blank=True, default=50, null=True)),
                ('building', models.CharField(blank=True, max_length=200, null=True)),
                ('endDate', models.DateField()),
            ],
        ),
    ]
