# Generated by Django 5.0.2 on 2024-03-19 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminUser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='progress',
            field=models.FloatField(default=0),
        ),
    ]
