# Generated by Django 5.0.2 on 2024-02-25 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='total_saving',
            field=models.FloatField(default=0),
        ),
    ]
