# Generated by Django 5.0.2 on 2024-02-27 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='time_logged',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
